#!/usr/bin/env bash
# This script finds and kills the 4-to_infinity_and_beyond process

# Get the PID of the running 4-to_infinity_and_beyond script
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If the process exists, kill it
if [ -n "$pid" ]; then
    kill "$pid"
fi
